---
debug           : true
recaptcha_pubkey: 6LerQrsSAAAAAK768_OCsBc8uf7KLlqofEVopSt1
recaptcha_prikey: 6LerQrsSAAAAAK0Z9QcFtZNGEnL1ARtBqOYptABp
mailhide_pubkey : 013lK5nSug0owYEdHGzuwFrA==
mailhide_prikey : 7e238da27498ccb66006d1dcf9ed629b
dbhost          : localhost
dbuser          : LMS_development
dbpass          : 
dbname          : LMS_development
user_agent      : ClassMate/0.1
